controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;
use app\models\Fias;
use app\models\Stat;
use app\models\Test;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) { // Если есть, загружаем post данные в модель через родительский метод load класса Model
            // $model->openpass = $model->password_repeat;
            if ($user = $model->signup()) { //Если регистрация
                if (Yii::$app->getUser()->login($user)) { //Логиним пользователя, если регистрация успешна
                    return $this->goHome();
                }
            }
        }
        return $this->render('signup', [//Просто рендерим вид, если один из if вернул false
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionFias()
    {
        $model = new Fias();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            return $this->render('fias-confirm', ['model' => $model,]);
        } else {
            return $this->render('fias', ['model' => $model,]);
        }
        //return $this->render('fias', ['model' => $model,]);
    }

    public function actionStat()
    {
        $model = new Stat();
//        if (Yii::$app->request->isPjax) {
//            $answer = true;
//            return $this->render('stat', compact('model', 'answer'));
//        }
        //return $this->render('stat', compact('model'));
        return $this->render('stat', ['model' => $model,]);
    }

    public function actionStreetLists()
    {
        $city_code = Yii::$app->request->post('citycode');
        $content = file_get_contents('http://basicdata.ru/api/json/fias/addrobj/' . $city_code . '/');
        $data = json_decode($content, true);

        foreach ($data['data'] as $street) {
            if ($street) {
                if ($street['actstatus'] == '1') {
                    $option[] = '<option value ="' . $street['aoguid'] . '">' . $street['shortname'] . '. ' . $street['formalname'] . '</option>';
                }
            }
        }

        if (count($option) > 0) {
            foreach ($option as $value) {
                echo $value;
            }
        } else {
            echo '<option> -Выберите значение-</option>';
            echo '<option value="' . $city_code . '"> -Улицы отсутствуют-</option>';
        }
    }

    public function actionHouseLists()
    {
        $street_code = Yii::$app->request->post('streetcode');
        $content = file_get_contents('http://basicdata.ru/api/json/fias/house/' . $street_code . '/');
        $data = json_decode($content, true);
        if (count($data) > 0) {
            foreach ($data['data'] as $house) {
                $stat = '';
                if ($house['eststatus'] == '1') {
                    $stat = 'владение';
                } elseif ($house['eststatus'] == '2') {
                    $stat = 'дом';
                } elseif ($house['eststatus'] == '3') {
                    $stat = 'домовладение';
                }
                echo '<option>' . $stat . ' ' . $house['housenum'] . '</option>';
            }
        } else {
            echo '<option>--Нет домов--</option>';
        }
    }

    public function actionTest()
    {
        $model = new Test();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->files = UploadedFile::getInstances($model, 'files');
            Test::compressImg($model->files);
        }
        return $this->render('test', ['model' => $model]);

    }


}

views/site/_modal_install_spravkabk.php
<?php
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<center><h2>Инструкция по установке <br> ПО "Справки БК"</h2></center>',
    'toggleButton' => [
        'label' => 'Помощь по установке программы',
        'class' => 'btn btn-info btn-block btn-lg'
    ],
    'footer' => 'По всем вопросам обращаться к Дешковичу С.С. тел: 5-06-25'
])
?>
<div class="container">
    <p>1. Качаем <a href="/uploads/programm/SpravkiBKsetup_ver._2.4.msi">установочный файл программы</a> в любое место</p>
    <p>2. Зпускаем скачанный файл</p>
    <p>3. Жмём "Далее", "Далее", "Далее", "Установить", "Готово"</p>
    <p>4. Откроется установленная программа.</p>
    <p>5. На рабочем столе появится вот такой . <img src="/img/shortcut_spo.png" alt="ярлык СПО"> ярлык программы. <br> <small>(Последующие запуски программы производятся с помощью этого ярлыка)</small></p>
    <p>6. Скачанный в п.1 установочный файл удалить (по желанию).</p>
    <p>7. Конец инструкции по установке</p>
</div>
<?php Modal::end(); ?>

views/site/_viewstat.php
<?php

use app\models\Stat;

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/fias.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use app\models\Fias;

$this->title = 'Пример использования API ФИАС';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
    <h1><?= Html::encode($this->title); ?> </h1>
    <div class="row">
        <div class="col-md-4">
            <?php
            //15784a67-8cea-425b-834a-6afe0e3ed61c Костромская область
            //a031240c-d73d-4c40-b839-fd880d6a777c Шарьинский район
            //http://basicdata.ru/api/json/fias/addrobj/a031240c-d73d-4c40-b839-fd880d6a777c/ - Населеные пункты ШМР
            //http://basicdata.ru/api/json/fias/addrobj/5c6b8394-8b66-4b4f-8bf6-9b256feb4a3a - Улицы Зебляков (AOGUID населенного пункта)
            //http://basicdata.ru/api/json/fias/house/e03e8c3b-1095-459c-8320-250d7b085c0a/ - Дома улицы Ветеранов (AOUGUID)
//            $content = file_get_contents('http://basicdata.ru/api/json/fias/addrobj/a031240c-d73d-4c40-b839-fd880d6a777c/');
//            $data = json_decode($content, true);
//            $np = $data['data'];
//            $items = array();
//            foreach ($np as $value) {
//                $name = $value['offname'];
//                if ($value['actstatus'] == '1') {
//                    $items[] = $value['shortname'] . '. ' . $value['offname'] . ' ОКАТО: ' . $value['okato'];
//                    $current_name = $name;
//                }
//            }
//
//            echo \yii\helpers\Html::dropDownList('Населенные пункты', '', $items, ['prompt' => 'выберите нп']);
//            echo '<br>';
//            $var_str = '5c6b8394-8b66-4b4f-8bf6-9b256feb4a3a';
//            $content_str = file_get_contents('http://basicdata.ru/api/json/fias/addrobj/' . $var_str . '/');
//            $dat_str = json_decode($content_str, true);
//            $streets = $dat_str['data'];
////
//            $var_house = 'ffd556b9-1eac-46e3-b7e8-110764482432';
//            $content_house = file_get_contents('http://basicdata.ru/api/json/fias/house/' . $var_house . '/');
//            $dat_houses = json_decode($content_house, true);
//            $houses = $dat_houses['data'];
//
//            echo \yii\helpers\VarDumper::dump($houses[0]) . '<br>';
//            echo \yii\helpers\VarDumper::dump($dat_str['data'][0]) . '<br>'; //Улицы
//            echo \yii\helpers\VarDumper::dump($np[119]); //Населенные пункты (119 - пос Зебляки)
            ?>
        </div>
    </div>
    <div class="container">
        <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-4">
                <?php $items = Fias::get_np(); //Получаем все населенные пункты района  ?> 
                <?php // echo \yii\helpers\VarDumper::dump($model) ?>
                <?php // echo \yii\helpers\VarDumper::dump($items); ?>
                <?=
                $form->field($model, 'aoguid_np')->DropDownList($items, [
                    'id' => 'np',
                    'prompt' => '-Выберите населённый пункт-',
                    'data-toggle' => 'dropdown',
                    'onchange' => '$.post("' . Url::toRoute('site/street-lists')
                    . '", {citycode: $(this).val()},'
                    . 'function(res){'
                    . '$("#street").html(res);'
                    . '$("#street").attr("disabled", false);'
                    . '$("#house").val(0);'
                    . '$("#house").attr("disabled", true);'
                    . '});',
                ])->label('Населённый пункт')
                ?>
            </div>
            <div class="col-md-4">
                <?=
                $form->field($model, 'aoguid_street')->DropDownList([], [
                    'id' => 'street',
                    'prompt' => '-Выберите улицу-',
                    'data-toggle' => 'dropdown',
                    'onchange' => '$.post("' . Url::toRoute('site/house-lists') . '", {streetcode: $(this).val()},'
                    . 'function(res){'
                    . '$("#house").html(res);'
                    . '$("#house").attr("disabled", false);'
                    . '});',
                ])->label('Улица')
                ?>
            </div>
            <div class="col-md-4">
                <?=
                $form->field($model, 'house')->dropDownList([], [
                    'id' => 'house',
                    'prompt' => '-Выберите дом-',
                    'data-toggle' => 'dropdown',
                ])->label('Дом')
                ?>
            </div>
        </div>
       
        <?php ActiveForm::end(); ?>
    </div>

</div>


views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use app\models\User;
use app\models\Siteinfo;
use app\models\Birthday;

$this->title = 'Сервисы администрации ШМР';

if (User::isAdmin()) {
    $countNotPublish = Siteinfo::find()->where(['si_status' => '1'])->count();
    if ($countNotPublish > 0) {
        $countInfo = '<span class="label label-danger">' . $countNotPublish . '</span>';
    } else {
        $countInfo = '<span class="label label-success">0</span>';
    }
} else {
    $countInfo = '';
}
?>
<div class="site-index">
    <div class="body-content">
        <div class="container">
            <div class="row" id="plashki">
                <div class="col-sm-4 col-md-4 col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading text-right">
                            <div class="pull-left">
                                <a href="<?= Url::to(['/siteinfo/index']) ?>"><?= Html::img('/img/info512.png', ['alt' => 'Инфо для сайта', 'width' => 40]) ?></a>
                            </div>
                            <a href="<?= Url::to(['/siteinfo/index']) ?>"><h4>Информация для сайта <?= $countInfo; ?></h4></a>
                        </div>
                        <div class="panel-body text-center">
                            <p>Инструмент отправки информации для последующего размещения на сайте администрации Шарьинского района.</p>
                            <a href="<?= Url::to(['/site/stat']) ?>"><span class="glyphicon glyphicon-stats"></span> Статистика отправки информации</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading text-right">
                            <div class="pull-left">
                                <a href="<?= Url::to(['/npa/index']) ?>"><?= Html::img('/img/document512.png', ['alt' => 'База НПА', 'width' => 40]) ?></a>
                            </div>
                            <a href="<?= Url::to(['/npa/index']) ?>"><h4>База документов администрации</h4></a>
                        </div>
                        <div class="panel-body">
                            <p class="text-center"><br>База внутренних документов администрации Шарьинского муниципального района</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading text-right">
                            <div class="pull-left">
                                <a href="<?= Url::to(['/birthday/index']) ?>"><?= Html::img('/img/cookie4406.png', ['alt' => 'Дни рождения', 'width' => 40]) ?></a>
                            </div>
                            <h4>Дни рождения<br>служащих</h4>
                        </div>
                        <div class="panel-body">
                            <?php
                            //Именинники
                            $mans = Birthday::getBirthdaymans();
                            //yii\helpers\VarDumper::dump($mans);
                            if ($mans) {
                                echo '<div style="height:60px;" class="text-right">';
                                echo Html::img('/img/hbsmile.png', ['alt' => 'День рождения!', 'width' => 60, 'class' => 'pull-left', 'style' => 'padding-right:10px;']);

                                echo '<h4>День рождения сегодня:</h4>';
                                echo '</div>';
                                echo '<div>';
                                echo '<ul class="birthday-list">';
                                foreach ($mans as $value) {
                                    if ($value->b_notes) {
                                        $value->b_notes = ' (' . $value->b_notes . ')';
                                    }
                                    //yii\helpers\VarDumper::dump($value);
                                    echo '<li class="text-right">';
                                    echo $value->b_fio . $value->b_notes . '<br><small>Д.р. ' . Birthday::getNormalizeDate($value->b_datbirth, $value->b_yearbirth) . '</small>';
                                    echo '</li>';
                                }
                                echo '</ul>';
                                echo '</div>';
                            } else {
                                echo Html::img('/img/hbgrsmile.png', ['alt' => 'Некого поздравлять', 'width' => 60, 'class' => 'pull-left', 'style' => 'padding-right:10px;']);
                                echo '<h4>Сегодня именинников нет</h4>';
                            }
                            ?>
                        </div>

                    </div>
                </div>
            </div>

            <!--            <div class="row" id="plashki">
            
                            <div class="col-sm-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading text-right">
                                        <div class="pull-left">
                                            <a href="<?= Url::to(['/violation/index']) ?>"><?= Html::img('/img/Rules48.png', ['alt' => 'Административные правонарушения', 'width' => 40]) ?></a>
                                        </div>
                                        <a href="#"><h4>Журнал административных правонарушений</h4></a>
                                    </div>
                                    <div class="panel-body">
                                        <p class="text-center">Учет административных правонарушений<br><br><span class="label label-danger">В разработке</span><br></p>
                                    </div>
                                </div>
                            </div>
            
                            <div class="col-sm-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading text-right">
                                        <div class="pull-left">
                                            <a href="<?= Url::to(['/reestrmi/index']) ?>"><?= Html::img('/img/reestr48.png', ['alt' => 'Реестр муниципального имущества', 'width' => 40]) ?></a>
                                        </div>
                                        <a href="#"><h4>Реестр муниципального имущества</h4></a>
                                    </div>
                                    <div class="panel-body">
                                        <p class="text-center"><br><br><span class="label label-danger">В разработке</span><br></p>
                                    </div>
                                </div>
                            </div>
            
                            <div class="col-sm-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading text-right">
                                        <div class="pull-left">
                                            <a href="<?= Url::to(['/journal/index']) ?>"><?= Html::img('/img/msg.png', ['alt' => 'Журнал корреспонденции', 'width' => 40]) ?></a>
                                        </div>
                                        <a href="#"><h4>Журнал<br>корреспонденции </h4></a>
                                    </div>
                                    <div class="panel-body">
                                        <p class="text-center">Учет входящей и исходящей корреспонденции. <br><br><span class="label label-danger">В разработке</span><br></p>
                                    </div>
                                </div>
                            </div>
            
                        </div>-->
<!--            <div class="row">-->
<!--                <div class="col-sm-12 col-md-12 col-lg-12">-->
<!--                    <a href="/uploads/programm/SpravkiBKsetup_ver._2.4.1.msi">-->
<!--                        <h1>Скачать программное обеспечение "Справки БК" (версия 2.4.1)</h1>-->
<!--                    </a>-->
<!--                    <h1><small>Подготовка справок о доходах, расходах, об имуществе и обязательствах имущественного характера</small></h1>-->
<!--                    <hr> -->
<!--                </div>-->
<!--            </div>      -->
<!--            <div class="row">-->
<!--                <div class="col-sm-6 col-md-6 col-lg-6">-->
<!--                    <a href="/uploads/programm/instr_BK.doc"><h3>Инструкция по работе с программным обеспечением "Справки БК"</h3></a>-->
<!--                </div>-->
<!--                <div class="col-sm-6 col-md-6 col-lg-6 helbtn">-->
<!--                    --><?php //require '_modal_install_spravkabk.php'; ?>
<!--                </div>-->
<!--            </div>-->
        </div>
    </div>
</div>

views/site/passwordReset.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

views/site/stat_15012018.php
<?php

use app\models\Siteinfo;
use app\models\Oldsiteinfo;
use app\models\Olddivision;
use app\models\Division;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Статистика предоставления информации на сайт';
$this->params['breadcrumbs'][] = $this->title;
$data = Yii::$app->request->post();
$startdata = '';
$start_data = '';
$end_data = '';
if ($data) {
    $start_data = $data['Stat']['start_data'];
    $end_data = $data['Stat']['end_data'];
}

if ($start_data) {
    $startdata = date('d.m.Y', strtotime($start_data));
} else {
    $startdata = date('d.m.Y', strtotime("last Monday"));
}
$enddata = date('d.m.Y', strtotime($end_data . '+1 day'));
$enddata_head = date('d.m.Y', strtotime($end_data . '+0 day'));

$lastMonday = Date('d.m.Y', strtotime('last Monday'));
$divisions = Siteinfo::findBySql('SELECT DISTINCT(si_division_id) FROM tbl_siteinfo WHERE si_data >= STR_TO_DATE("' . $startdata . '", "%d.%m.%Y") AND si_data <= STR_TO_DATE("' . $enddata . '", "%d.%m.%Y")')->all(); // AND si_data < STR_TO_DATE("' . $enddata . '", "%d.%m.%Y")
//echo \yii\helpers\VarDumper::dump($enddata_head);
?>

<div class="container-fluid center-block">
    <div class="row">

        <div style="height: 40px; float: right; cursor: hand;">
            <span class="noprint"><svg height="30" width="30" onclick="print()"><path d="M4,2h8v2h1V1H3v3h1M0,5v6h3v1l3,3h7v-4h3V5m-3,2v1H12v6H6V12H4V8H3V7m2,1h6v1H5m0,1h6v1H5"></path></svg></span>
        </div>
    </div>
    <div class="row">
        <h3 class="text-center">Обобщенная информация<br>о предоставленных материалах на сайт администрации Шарьинского района<br>в период с '<?= $startdata ?>' по '<?= $enddata_head ?>'<br><small>по состоянию на <?= Date('Hчас. iмин. d.m.Y') ?></small></h3>
        <div class="col-md-12">
            <table class="table table-striped table-bordered">
                <tr><th class="text-center">Подразделение</th><th class="text-center">Наименование материала</th><th class="text-center">Дата отправки</th></tr>
                <?php
                foreach ($divisions as $key => $value) {
                    $divid = $value['si_division_id'];
                    $userID = $value['si_user_id'];
                    $divname = Division::findOne(['div_id' => $divid])->div_name;


                    //Получаем инфу подразделения за период
                    $info = Siteinfo::findBySql('SELECT si_name_info, si_user_id, si_data FROM tbl_siteinfo WHERE si_division_id = ' . $divid . ' AND si_data >= STR_TO_DATE("' . $startdata . '", "%d.%m.%Y") AND si_data <= STR_TO_DATE("' . $enddata . '", "%d.%m.%Y")')->all();
                    echo '<tr>';
                    if (count($info) >= 2) {
                        echo '<td rowspan="' . count($info) . '">';
                    } else {
                        echo '<td>';
                    }

                    echo $divname . '<br><span class="label label-success">' . count($info) . 'шт.</span>';
                    echo '</td>';
                    //Добавляем наименования информаций
                    foreach ($info as $key => $value) {
                        echo '<td>';
                        echo $value->si_name_info;
                        echo '</td>';
                        echo '<td>';
                        echo '<span class="label label-info">' . date('d.m.Y', strtotime($value->si_data)) . '</span>';
                        echo '</td>';
                        echo '</tr>';
                    }
                }
                ?>
            </table>
        </div>
    </div>
    <div class="row" id="po-godam">
        <h1 class="text-center">Количество предоставленной информации, по годам</h1>
        <h3 class="text-center">период с '<?= Date('d.m', strtotime($startdata)) ?>' по '<?= substr($enddata_head, 0, strlen($enddata) - 5) ?>'</h3>
        <div class="col-md-12">
            <table class="table table-hover table-bordered">
                <tr><th>Подразделение</th><th>2017</th><th>2016</th><th>2015</th><th>2014</th></tr>
                <?php
                foreach ($divisions as $key => $value) {
                    $divid = $value['si_division_id'];

                    $divname = Division::findOne(['div_id' => $divid])->div_name;
                    //Количество инфы за период 2017 года
                    $count2017 = Siteinfo::findBySql('SELECT * FROM tbl_siteinfo WHERE si_division_id = ' . $divid . ' AND si_data >= STR_TO_DATE("' . $startdata . '", "%d.%m.%Y") AND si_data <= STR_TO_DATE("' . $enddata . '", "%d.%m.%Y")')->all();
                    //Получем ID для подразделения старой базы
                    if ($divname){
                        $oldID = Olddivision::getIdByDivisionName($divname);
                    }
                    
                    if ($oldID) {
                        //Получаем инфу подразделения за период 2016

                        $sdate2016 = substr($startdata, 0, strlen($startdata) - 1) . 6;
                        $edate2016 = substr($enddata, 0, strlen($enddata) - 1) . 6;

                        $count2016 = Oldsiteinfo::findBySql('SELECT * FROM tbl_oldsiteinfo WHERE KONTORA_ID = ' . $oldID . ' AND DATA >= STR_TO_DATE("' . $sdate2016 . '", "%d.%m.%Y") AND DATA <= STR_TO_DATE("' . $edate2016 . '", "%d.%m.%Y")')->all();

                        //Получаем инфу подразделения за период 2015

                        $sdate2015 = substr($startdata, 0, strlen($startdata) - 1) . 5;
                        $edate2015 = substr($enddata, 0, strlen($enddata) - 1) . 5;

                        $count2015 = Oldsiteinfo::findBySql('SELECT * FROM tbl_oldsiteinfo WHERE KONTORA_ID = ' . $oldID . ' AND DATA >= STR_TO_DATE("' . $sdate2015 . '", "%d.%m.%Y") AND DATA <= STR_TO_DATE("' . $edate2015 . '", "%d.%m.%Y")')->all();

                        //Получаем инфу подразделения за период 2015

                        $sdate2014 = substr($startdata, 0, strlen($startdata) - 1) . 4;
                        $edate2014 = substr($enddata, 0, strlen($enddata) - 1) . 4;

                        $count2014 = Oldsiteinfo::findBySql('SELECT * FROM tbl_oldsiteinfo WHERE KONTORA_ID = ' . $oldID . ' AND DATA >= STR_TO_DATE("' . $sdate2014 . '", "%d.%m.%Y") AND DATA <= STR_TO_DATE("' . $edate2014 . '", "%d.%m.%Y")')->all();
                        echo '<tr>';
                        echo '<td>' . $divname . '</td>';
                        //Добавляем кол-во информаций
                        echo '<td>' . count($count2017) . '</td>';
                        echo '<td>' . count($count2016) . '</td>';
                        echo '<td>' . count($count2015) . '</td>';
                        echo '<td>' . count($count2014) . '</td>';
                        echo '</tr>';
                        //\yii\helpers\VarDumper::dump($count2017);
                    }
                }
                ?>
            </table>
        </div>
    </div>

    <?php Pjax::begin() ?>
    <?php
    $form = ActiveForm::begin([
                'id' => 'stat-form',
                'action' => Url::to(['site/stat']),
    ]);
    ?>
    <div class="row noprint">
        <div class="col-md-2 col-md-offset-4">
            <?= $form->field($model, 'start_data')->input('date')->label('Начало периода') ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'end_data')->input('date')->label('Конец периода') ?>
        </div>
    </div>
    <div class="row noprint">
        <div class="form-group col-md-4 col-md-offset-4">
            <?=
            Html::submitButton('Показать', [
                'class' => 'btn btn-success btn-block btn-lg'])
            ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
    <?php Pjax::end() ?>

</div>

views/site/test.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Тестовая страница';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container site-test">
    <h1><?= Html::encode($this->title); ?> </h1>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin([
                    'id' => 'form-signup',
            ]); ?>

            <?= $form->field($model, 'files[]')->fileInput([
                'multiple' => true,
                'class' => 'btn btn-default btn-block',
            ])->label('Вложения (Выбирать файлы необходимо все и сразу!)'); ?>

            <div class="form-group">
                <?= Html::submitButton('Загрузить', ['class' => 'btn btn-primary', 'name' => 'signup-button']); ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
    <?php \yii\helpers\VarDumper::dump($model, 5, true) ?>
</div>