models/Npa.php
<?php

namespace app\models;

use Yii;
use ZipArchive;

/**
 * This is the model class for table "{{%npa}}".
 *
 * @property string $npa_id
 * @property string $npa_number
 * @property string $npa_literanumber
 * @property string $npa_date_adoption
 * @property string $npa_date_start
 * @property string $npa_sign_user_id
 * @property string $npa_vestnik_id
 * @property string $npa_div_id
 * @property string $npa_user_id
 * @property string $npa_path
 * @property string $npa_title
 * @property string $npa_text
 */
class Npa extends \yii\db\ActiveRecord {

    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%npa}}';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['npa_number', 'npa_sign_user_id', 'npa_vestnik_id', 'npa_div_id', 'npa_user_id', 'npa_view_id', 'npa_type_id'], 'integer'],
            [['npa_date_adoption', 'npa_date_start'], 'safe'],
            [['npa_number', 'npa_path', 'npa_title', 'npa_text'], 'required'],
            [['npa_title', 'npa_text'], 'string'],
            [['npa_literanumber'], 'string', 'max' => 10],
            [['npa_fullnumber'], 'string', 'max' => 20],
            [['npa_path'], 'string', 'max' => 300],
            [['npa_number'], 'unique', 'targetAttribute' => ['npa_type_id','npa_number', 'npa_literanumber', 'npa_date_adoption'], 'message' => 'Такой документ уже есть в базе!'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'npa_id' => 'Код',
            'npa_number' => 'Основной номер',
            'npa_literanumber' => 'Доп. номер',
            'npa_fullnumber' => 'Номер',
            'npa_date_adoption' => 'Дата',
            'npa_date_start' => 'Дата начала действия',
            'npa_sign_user_id' => 'Кем подписан документ',
            'npa_vestnik_id' => 'Код вестника',
            'npa_div_id' => 'Код подразделения, ответсвенного за подготовку',
            'npa_user_id' => 'Код служащего, разместившего документ',
            'npa_path' => 'Путь к файлу',
            'npa_title' => 'Заголовок документа',
            'npa_text' => 'Текст документа',
            'npa_view_id' => 'Вид документа',
            'npa_type_id' => 'Тип документа',
        ];
    }

    public static function zipfile($sourceFile, $destfile, $filename) {
        $zip = new ZipArchive();
        if (!$zip->open($destfile, ZIPARCHIVE::CREATE)) {
            exit("Не могу открыть " . $destfile . '<br>');
        }
        $zip->addFile($sourceFile->tempName, $filename);
        $zip->close();
        unset($zip);
    }

    public static function get_trans_typename($model) {
        switch (Npatype::findOne(['ntype_id' => $model->npa_type_id])->ntype_name) {
            case 'Постановление':
                return 'Post';
            case 'Распоряжение':
                return 'Rasp';
            case 'Решение':
                return 'Resh';
            case 'Приказ':
                return 'Prikaz';
        }
    }

    public static function get_typename($id) {
        return Npatype::findOne(['ntype_id' => $id])->ntype_name;
    }

    public static function get_viewname($id) {
        return Npaview::findOne(['nview_id' => $id])->nview_name;
    }

    public static function isAutor($model) {
        if ($model->npa_user_id == Yii::$app->user->identity->id) {
            return true;
        } else {
            return false;
        }
    }

}

models/Npatype.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%npatype}}".
 *
 * @property string $ntype_id
 * @property string $ntype_name
 */
class Npatype extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%npatype}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ntype_name'], 'required'],
            [['ntype_name'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ntype_id' => 'Ntype ID',
            'ntype_name' => 'Ntype Name',
        ];
    }
}

models/Npaview.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%npaview}}".
 *
 * @property string $nview_id
 * @property string $nview_name
 */
class Npaview extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%npaview}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nview_name'], 'required'],
            [['nview_name'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nview_id' => 'Nview ID',
            'nview_name' => 'Nview Name',
        ];
    }
}

controllers/NpaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Npa;
use app\models\NpaSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Inflector;
use app\models\User;
use yii\web\ForbiddenHttpException;


/**
 * NpaController implements the CRUD actions for Npa model.
 */
class NpaController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Npa models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NpaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Npa model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Npa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Npa();
        if ($model->load(Yii::$app->request->post())) {

            $model->npa_fullnumber = $this->get_npa_fullnumber($model);

            $model->file = UploadedFile::getInstance($model, 'file');

            $path_dest_dir = $this->set_path_dest_dir('uploads/documents/npa');

            $model->npa_path = $path_dest_dir . '/' . Npa::get_trans_typename($model) . Inflector::transliterate(mb_strtolower($model->npa_fullnumber)) . '_' . date('d.m.Y', strtotime($model->npa_date_adoption)) . '.zip';

            $model->npa_user_id = Yii::$app->user->identity->id;
        }

        if ($model->save()) {
            if (!$model->file) {
                $model->addError($attribute, 'Необходимо прикрепить файл с документом.');
                return $this->render('create', ['model' => $model]);
            }
            if ($model->file && $model->validate()) {
                //$path = $path_dest_dir . '/' . Npa::get_trans_typename($model) . Inflector::transliterate(mb_strtolower($model->npa_fullnumber)) . '_' . date('d.m.y', $model->npa_date_adoption) . '.' . $model->file->extension; //отображает корректно руские названия файлов
                Npa::zipfile($model->file, $model->npa_path, Inflector::transliterate(mb_strtolower($model->file->baseName)) . '.' . $model->file->extension);
            }
            return $this->redirect(['view', 'id' => $model->npa_id]);
        } else {
            return $this->render('create', ['model' => $model]);
        }
    }

    /**
     * Updates an existing Npa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {

            $old_file = $model->npa_path;

            $model->npa_fullnumber = $this->get_npa_fullnumber($model);

            $model->file = UploadedFile::getInstance($model, 'file');

            $path_dest_dir = $this->set_path_dest_dir('uploads/documents/npa');

            $model->npa_path = $path_dest_dir . '/' . Npa::get_trans_typename($model) . Inflector::transliterate(mb_strtolower($model->npa_fullnumber)) . '_' . date('d.m.Y', strtotime($model->npa_date_adoption)) . '.zip';

            $model->npa_user_id = Yii::$app->user->identity->id;
        }

        if ($model->save()) {
            if (!$model->file) {
                $model->addError($attribute, 'Необходимо прикрепить файл с документом.');
                return $this->render('create', ['model' => $model]);
            }
            if ($model->file && $model->validate()) {
                if (file_exists($old_file)) {
                    unlink($old_file);
                }
                //$path = $path_dest_dir . '/' . Npa::get_trans_typename($model) . Inflector::transliterate(mb_strtolower($model->npa_fullnumber)) . '_' . date('d.m.y', $model->npa_date_adoption) . '.' . $model->file->extension; //отображает корректно руские названия файлов
                Npa::zipfile($model->file, $model->npa_path, Inflector::transliterate(mb_strtolower($model->file->baseName)) . '.' . $model->file->extension);
            }
            return $this->redirect(['view', 'id' => $model->npa_id]);
        } else {
            return $this->render('update', ['model' => $model]);
        }
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            
//            return $this->redirect(['view', 'id' => $model->npa_id]);
//        } else {
//            return $this->render('update', [
//                        'model' => $model,
//            ]);
//        }
    }

    /**
     * Deletes an existing Npa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Npa::isAutor($this->findModel($id)) or User::isAdmin()) {

            $target_file = Npa::findOne(['npa_id' => $id])->npa_path;

            if ($this->findModel($id)->delete()) {
                if (file_exists($target_file)) {
                    unlink($target_file);
                }
            }
        } else {
            throw new ForbiddenHttpException('Удаление невозможно. Доступ запрещен');
        }
        return $this->redirect(['index']);
    }

    public function actionFiles($id)
    {
        $model = $this->findModel($id);
        return $this->render('files', ['model' => $this->findModel($id)]);
    }

    /**
     * Finds the Npa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Npa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Npa::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не существует.');
        }
    }

    public function get_npa_fullnumber($model)
    {
        if ($model->npa_literanumber) {
            return $model->npa_number . '-' . $model->npa_literanumber;
        } else {
            return $model->npa_number;
        }
    }

    public function set_path_dest_dir($path_dest_dir)
    {
        if (!$path_dest_dir) {
            mkdir($path_dest_dir, 0777, true);
        }
        return $path_dest_dir;
    }

}

views/npa/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\User;
use app\models\Division;
use app\models\Npaview;
use app\models\Npatype;

/* @var $this yii\web\View */
/* @var $model app\models\Npa */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="npa-form">


    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6">
            <?php $view_items = ArrayHelper::map(Npaview::find()->all(), 'nview_id', 'nview_name') ?>
            <?= $form->field($model, 'npa_view_id')->dropDownList($view_items)->label('Вид документа') ?>
        </div>
        <div class="col-md-6">
            <?php $type_items = ArrayHelper::map(Npatype::find()->all(), 'ntype_id', 'ntype_name') ?>
            <?= $form->field($model, 'npa_type_id')->dropDownList($type_items)->label('Тип документа') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'npa_number')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'npa_literanumber')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'npa_date_adoption')->Input('date', ['value' => date('Y-m-d')]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'npa_date_start')->Input('date', ['value' => date('Y-m-d')]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php $items = ArrayHelper::map(User::find()->where(['in', 'role', [User::ROLE_BOSS, User::ROLE_BOSS_ASSISTANT, User::ROLE_HEAD_DIVISION]])->all(), 'id', 'fio'); ?>
            <?= $form->field($model, 'npa_sign_user_id')->dropDownList($items) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php $div_items = ArrayHelper::map(Division::find()->orderBy(['div_name' => 'ASC'])->all(), 'div_id', 'div_name'); ?>
            <?= $form->field($model, 'npa_div_id')->dropDownList($div_items, ['prompt' => 'Выберите подразделение'])->label('Подразделение, ответственное за подготовку') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'npa_title')->textarea(['rows' => 6, 'placeholder' => 'Например: Об утверждении отчета о реализации программы оздоровления муниципальных финансов за  1 полугодие 2017 года']) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'npa_text')->textarea(['rows' => 6, 'placeholder' => 'Например: Руководствуясь Соглашением №15 от 25.01.2017 года «О мерах по повышению эффективности использования бюджетных средств и увеличению поступлений налоговых и неналоговых доходов местного бюджета Шарьинского муниципального района», заключённого между департаментом финансов Костромской области и администрацией Шарьинского муниципального района, а также п.19 ч.1 ст. 36,ст.38,42 Устава муниципального образования Шарьинский муниципальный район...'])->label('текст документа')->label('Текст документа (вместе с приложениями)') ?>
        </div>
    </div>
    <?php //echo $form->field($model, 'npa_path')->textInput(['maxlength' => true]) ?>
    <?php
    if ($model->isNewRecord) {
        echo $form->field($model, 'file')->fileInput([
            'multiple' => false,
            'class' => 'btn btn-default btn-block',
        ])->label('Документ вместе с приложениями (одним файлом)');
    } else {
        echo Html::tag('div', Html::a('Просмотр прикрепленных файлов:<br>' . basename($model->npa_path), $model->npa_path, ['class' => 'btn btn-info', 'target' => 'blank']), ['class' => 'col-md-3'])  ; //Url::to(['/npa/files', 'id' => $model->npa_id]), ['class' => 'btn btn-info view-files', 'target' => 'blank']),['class' => 'col-md-3'])
        //echo Html::a('Просмотр прикрепленных файлов', Url::to(['/npa/files', 'id' => $model->npa_id]), ['class' => 'btn btn-info view-files', 'target' => 'blank']);
//        echo $form->field($model, 'file')->fileInput([
//            'multiple' => false,
//            'class' => 'btn btn-default btn-block',
//        ])->label('Постановление вместе с приложениями (одним файлом)');
        echo Html::tag('div', $form->field($model, 'file')->fileInput([
            'multiple' => false,
            'class' => 'btn btn-default btn-block',
        ])->label('Прикрепить постановление вместе с приложениями (одним файлом)'), ['class' => 'col-md-9']);
    }
    ?>
    <div class="form-group text-right">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить документ' : 'Сохранить изменения', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/npa/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NpaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="npa-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'npa_id') ?>

    <?= $form->field($model, 'npa_number') ?>

    <?= $form->field($model, 'npa_literanumber') ?>

    <?= $form->field($model, 'npa_date_adoption') ?>

    <?= $form->field($model, 'npa_date_start') ?>

    <?php // echo $form->field($model, 'npa_sign_user_id') ?>

    <?php // echo $form->field($model, 'npa_vestnik_id') ?>

    <?php // echo $form->field($model, 'npa_div_id') ?>

    <?php // echo $form->field($model, 'npa_user_id') ?>

    <?php // echo $form->field($model, 'npa_path') ?>

    <?php // echo $form->field($model, 'npa_title') ?>

    <?php // echo $form->field($model, 'npa_text') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/npa/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Npa */

$this->title = 'Добавление документа';
$this->params['breadcrumbs'][] = ['label' => 'Документы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="npa-create">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>

        <?=
        $this->render('_form', [
            'model' => $model,
        ])
        ?>
    </div>
</div>

views/npa/files.php
<?php

use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Siteinfo;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\FileHelper;
use yii\helpers\Url;
use app\models\Npa;


$zipPath = "D:/nasait";
//$path = 'uploads/siteinfo';
$sourcefile = $model->npa_path;
$this->title = Npa::get_typename($model->npa_type_id) . ' №' . $model->npa_fullnumber . ' от ' . date('d.m.Y', strtotime($model->npa_date_adoption));
$this->params['breadcrumbs'][] = ['label' => 'Документы администрации', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['view', 'id' => $model->npa_id]];
$this->params['breadcrumbs'][] = 'Файлы';
?>

<div class="container siteinfo-files">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php
//    $files = scandir($path);
//    foreach ($files as $file) {
//        if (is_file($path . '/' . $file) == TRUE) {
//            $filelist[] = $file;
//        }
//    }
//    \yii\helpers\VarDumper::dump($filelist);
//    $filelist = FileHelper::findFiles($path);
//    \yii\helpers\VarDumper::dump($filelist);
    ?>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Имя файла</th>
                <th>Размер</th>
                <th>...</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (file_exists($sourcefile)) {
                        echo '<tr>';
                        echo '<td>1</td>';
                        echo '<td>';
                        echo Html::a(basename($sourcefile), $sourcefile);
                        echo '</td>';
                        echo '<td>' . round(filesize($sourcefile) / 1024) . ' Кб</td>';
                        echo '<td>';
                        //echo 'Сжать';
                        echo '</td>';
                        echo '</tr>';
                    }
                
            
            ?>
        </tbody>
    </table>
    <div class="pull-left">
        <?php Pjax::begin(); ?>
        <?php //echo Html::a('Копировать файлы (Путь: ' . $destFilepath . ')', ['siteinfo/copyfiles', 'id' => $model->si_id, 'sourceDir' => $sourcedir, 'destDir' => $destFilepath], ['class' => 'btn btn-lg btn-primary']); ?>
        <?php
        if ($count > 0) {
            echo '<script>alert("Скопировано файлов: ' . $count . '")</script>';
        }
        if ($zippedcount > 0) {
            echo '<script>alert("Заархивировано файлов: ' . $zippedcount . '")</script>';
        }
        ?>
        <?php Pjax::end(); ?>
    </div>
</div>

views/npa/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Npatype;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NpaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Документы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid npa-index">
    <div class="col-md-10 col-sm-12 text-center">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="col-md-2 col-sm-12 text-center">
        <h1>
            <?= Html::a('Добавить документ', ['create'], ['class' => 'btn btn-success']) ?>
        </h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php Pjax::begin(); ?>    
            <?=
            GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'attribute' => 'npa_type_id',
                        'value' => function ($data) {
                            return Npatype::findOne(['ntype_id' => $data->npa_type_id])->ntype_name;
                        },
                    ],
                    'npa_fullnumber',
                    [
                        'attribute' => 'npa_date_adoption',
                        'value' => function ($data) {
                            return date('d.m.Y', strtotime($data->npa_date_adoption));
                        },
                    ],
                    'npa_title:ntext',
                    [
                        'attribute' => 'npa_text',
                        'value' => function ($data) {
                            return mb_substr($data->npa_text, 0, 300, 'UTF-8') . '...';
                        }
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]);
            ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>

views/npa/update.php
<?php

use yii\helpers\Html;
use yii\web\ForbiddenHttpException;
use app\models\Npa;
use app\models\User;


/* @var $this yii\web\View */
/* @var $model app\models\Npa */

$this->title = Npa::get_typename($model->npa_type_id) . ' №' . $model->npa_fullnumber . ' от ' . date('d.m.Y года', strtotime($model->npa_date_adoption));
$this->params['breadcrumbs'][] = ['label' => 'Документы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['view', 'id' => $model->npa_id]];
$this->params['breadcrumbs'][] = 'Внесение изменений';
?>
<div class="npa-update">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>

        <?php
        if (Npa::isAutor($model->npa_id) or User::isAdmin()) {
            echo $this->render('_form', ['model' => $model]);
        } else {
            throw new ForbiddenHttpException('Изменение невозможно. Доступ запрещен');
        }
        
        ?>
    </div>
</div>

views/npa/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use app\models\Npatype;
use app\models\User;
use app\models\Division;

/* @var $this yii\web\View */
/* @var $model app\models\Npa */
/* @var $model app\models\User */
/* @var $model app\models\Division */

$typedoc = Npatype::findOne(['ntype_id' => $model->npa_type_id])->ntype_name;

$this->title = $typedoc . ' №' . $model->npa_fullnumber . ' от ' . date('d.m.Y года.', strtotime($model->npa_date_adoption));
$this->params['breadcrumbs'][] = ['label' => 'Документы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="npa-view">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('Изменить', ['update', 'id' => $model->npa_id], ['class' => 'btn btn-primary']) ?>
            <?=
            Html::a('Удалить', ['delete', 'id' => $model->npa_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Действительно удлаить ' . $this->title . '?',
                    'method' => 'post',
                ],
            ])
            ?>
        </p>

        <?=
        DetailView::widget([
            'model' => $model,
            'attributes' => [
                'npa_id',
                //'npa_number',
                //'npa_literanumber',
                'npa_fullnumber',
                [
                    'attribute' => 'npa_date_adoption',
                    'value' => date('d.m.Y', strtotime($model->npa_date_adoption))
                ],
                [
                    'attribute' => 'npa_date_start',
                    'value' => date('d.m.Y', strtotime($model->npa_date_start))
                ],
                [
                    'attribute' => 'npa_sign_user_id',
                    'value' => User::getShortname(User::get_fio_by_userid($model->npa_sign_user_id)),
                ],
                //'npa_vestnik_id',
                [
                    'attribute' => 'npa_div_id',
                    'value' => Division::findOne(['div_id' => $model->npa_div_id])->div_name,
                    'label' => 'Подразделение ответственное за подготовку',
                ],
                //'npa_user_id',
                [
                    'attribute' => 'npa_path',
                    'format' => 'raw',
                    'value' => function ($data) {
                        if (file_exists($data->npa_path)) {
                            return Html::a(basename($data->npa_path), $data->npa_path);
                        } else {
                            return '<div class="alert alert-danger" role="alert">Файл не найден!</div>';
                        }
                    },
                    //'value' => yii\helpers\VarDumper::dump(file_exists($model->npa_path)),
                    'label' => 'Файл',
                ],
                'npa_title:ntext',
                'npa_text:ntext',
            ],
        ])
        ?>
    </div>
</div>