models/Vestnik.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use ZipArchive;

/**
 * This is the model class for table "{{%vestnik}}".
 *
 * @property string $vest_id
 * @property string $vest_number
 * @property string $vest_numberlitera
 * @property string $vest_pathfile
 * @property string $vest_data
 */
class Vestnik extends ActiveRecord
{

    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%vestnik}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vest_number', 'vest_stat'], 'integer'],
            [['vest_pathfile'], 'required'],
            [['vest_data'], 'safe'],
            [['vest_fullnumber'], 'string', 'max' => 10],
            [['vest_numberlitera'], 'string', 'max' => 10],
            [['vest_pathfile'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'vest_id' => 'Код',
            'vest_number' => 'Номер',
            'vest_numberlitera' => 'Доп. номер',
            'vest_fullnumber' => 'Номер',
            'vest_pathfile' => 'Путь к файлу',
            'vest_data' => 'Дата',
            'vest_stat' => 'Статус размещения'
        ];
    }

    /**
     * @param $sourceFile
     * @param $destfile
     * @param $filename
     */
    public static function zipFile($sourceFile, $destfile, $filename)
    {
        $zip = new ZipArchive();
        if (!$zip->open($destfile, ZIPARCHIVE::CREATE)) {
            exit("Не могу открыть " . $destfile . '<br>');
        }
        $zip->addFile($sourceFile->tempName, $filename);
        $zip->close();
        unset($zip);
    }

    /**
     * @param $model
     * @return string
     */
    public static function setNewPath($model)
    {
        $old_path = $model->vest_pathfile;
//        $filename = substr($old_path, strrpos($old_path, '/') + 1);
        $dir_path = substr($old_path, 0, strrpos($old_path, '/') + 1);
        $newpath = $dir_path . 'Vestnik' . $model->vest_fullnumber . '_' . date('Y', strtotime($model->vest_data)) . '.zip';
        if ($old_path && $newpath) {
            rename($old_path, $newpath);
        }

        return $newpath;
    }

    /**
     * @param $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($this->vest_numberlitera) {
            $this->vest_fullnumber = $this->vest_number . '-' . $this->vest_numberlitera;
        } else {
            $this->vest_fullnumber = $this->vest_number;
        }
        $model = new Siteinfo();

        $model->si_user_id = app()->user->id;
        $model->si_division_id = app()->user->identity->division_id;
        $model->si_data = date('Y-m-d H:i');
        $model->si_name_info = 'Вестник Шарьинского района №' . $this->vest_fullnumber . ' от ' . date('d.m.Yг.', strtotime($this->vest_data));
        $model->si_map_id = '16';
        $model->si_end_public = $model->si_data;
        $model->si_path_attach = $this->vest_pathfile;
        $model->save();
        return true;
    }

}

controllers/VestnikController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Vestnik;
use app\models\VestnikSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\web\UploadedFile;

/**
 * VestnikController implements the CRUD actions for Vestnik model.
 */
class VestnikController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Vestnik models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new VestnikSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Vestnik model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Vestnik model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Vestnik();
        $pathDestinationDirectory = 'uploads/documents/vestnik';

        if ($model->load(Yii::$app->request->post())) {
            if ($model->vest_numberlitera) {
                $model->vest_fullnumber = $model->vest_number . '-' . $model->vest_numberlitera;
            } else {
                $model->vest_fullnumber = $model->vest_number;
            }

            $model->file = UploadedFile::getInstance($model, 'file');
            if (!is_dir($pathDestinationDirectory)) {
                mkdir($pathDestinationDirectory, 0777, TRUE);
            }
            $model->vest_pathfile = $pathDestinationDirectory . '/Vestnik' . $model->vest_fullnumber . '_' . date('Y', strtotime($model->vest_data)) . '.zip';

            if (!$model->file) {
                $model->addError('warning', 'Необходимо прикрепить файл с вестником.');
                return $this->render('create', [
                            'model' => $model,]);
            }
        }

        if ($model->save()) {
            if ($model->file && $model->validate()) {
                $path = $pathDestinationDirectory . '/Vestnik' . $model->vest_fullnumber . '_' . $model->vest_data . '.' . $model->file->extension; //отображает корректно руские названия файлов
                Vestnik::zipFile($model->file, $model->vest_pathfile, Inflector::transliterate(mb_strtolower($model->file->baseName)) . '.' . $model->file->extension);
                $model->file->saveAs($path);
            }
            return $this->redirect(['view', 'id' => $model->vest_id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Vestnik model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $model->vest_pathfile = Vestnik::setNewPath($model);//какая-то ебанина, переименовывает файл при втором заходе в редактирование
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vest_id]);
            
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }


    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id) {

        $file = Vestnik::findOne(['vest_id' => $this->findModel($id)->vest_id])->vest_pathfile;
        if (file_exists($file)) {
            unlink($file);
        }
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Vestnik model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Vestnik the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Vestnik::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('Запрашиваемая страница не существует.');
        }
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionFiles($id) {
        $model = $this->findModel($id);
        return $this->render('files', ['model' => $model]);
    }
    
    

}

views/vestnik/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Vestnik */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vestnik-form">
    <div class="container">
        <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-2">
                <?= $form->field($model, 'vest_number')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'vest_numberlitera')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'vest_data')->Input('date', ['value' => date('Y-m-d')]) ?>
            </div>
            <div class="col-md-6">
                <?php //echo $form->field($model, 'vest_pathfile')->textInput(['maxlength' => true]) ?>
                <?php
                if ($model->isNewRecord) {
                    echo $form->field($model, 'file')->fileInput([
                        'multiple' => FALSE,
                        'class' => 'btn btn-default btn-block',
                    ])->label('Вложение');
                } else {
                    $dir = $model->vest_pathfile;
                    echo '<span><b>Вложение<b></span>';
                    echo Html::a($dir, Url::to(['/vestnik/files', 'id' => $model->vest_id]), ['class' => 'btn btn-info view-files btn-block', 'target' => 'blank']);
                }
                ?>
            </div>

        </div>

        <div class="row">
            <div class="col-md-2 col-md-offset-10">
                <?php echo Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить изменения', ['class' => $model->isNewRecord ? 'btn btn-success btn-block' : 'btn btn-primary btn-block']) ?>
            </div>
        </div>


        <?php ActiveForm::end(); ?>
    </div>
</div>

views/vestnik/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VestnikSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vestnik-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'vest_id') ?>

    <?= $form->field($model, 'vest_number') ?>

    <?= $form->field($model, 'vest_numberlitera') ?>

    <?= $form->field($model, 'vest_pathfile') ?>

    <?= $form->field($model, 'vest_data') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vestnik/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Vestnik */

$this->title = 'Добавить Вестник';
$this->params['breadcrumbs'][] = ['label' => 'Вестник Шарьинского района', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container vestnik-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vestnik/files.php
<?php

use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Siteinfo;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\FileHelper;
use yii\helpers\Url;


$sourcepath = $model->vest_pathfile;
$this->title = 'Вестник №' . $model->vest_fullnumber . ' от ' . $model->vest_data;
$this->params['breadcrumbs'][] = ['label' => 'Вестник шарьинского района', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container siteinfo-files">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php
//    $files = scandir($path);
//    foreach ($files as $file) {
//        if (is_file($path . '/' . $file) == TRUE) {
//            $filelist[] = $file;
//        }
//    }
//    \yii\helpers\VarDumper::dump($filelist);
//    $filelist = FileHelper::findFiles($path);
//    \yii\helpers\VarDumper::dump($filelist);
    ?>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Имя файла</th>
                <th>Размер</th>
                <th>...</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if ($sourcepath) {
                $files = scandir($sourcepath);
                $num = 0;
                foreach ($files as $file) {
                    $fullpath = $sourcepath . '/' . $file;
                    if (is_file($fullpath) == TRUE) {
                        $num += 1;
                        echo '<tr>';
                        echo '<td>' . $num . '</td>';
                        echo '<td>';
                        echo $file;
                        echo '</td>';
                        echo '<td>' . round(filesize($fullpath) / 1024) . ' Кб</td>';
                        echo '<td>';
                        echo 'Скачать';
                        echo '</td>';
                        echo '</tr>';
                    }
                }
            }
            ?>
        </tbody>
    </table>
    <div class="pull-left">
        <?php Pjax::begin(); ?>
        <?= Html::a('Архивировать (Путь: ' . $zipPath . ')', ['siteinfo/zipdirectory', 'id' => $model->si_id, 'sourceDir' => $sourcepath, 'destDir' => $zipPath], ['class' => 'btn btn-lg btn-primary']); ?>
        <?= Html::a('Копировать файлы (Путь: ' . $destFilepath . ')', ['siteinfo/copyfiles', 'id' => $model->si_id, 'sourceDir' => $sourcepath, 'destDir' => $destFilepath], ['class' => 'btn btn-lg btn-primary']); ?>
        <?php
        if ($count > 0) {
            echo '<script>alert("Скопировано файлов: ' . $count . '")</script>';
        }
        if ($zippedcount > 0) {
            echo '<script>alert("Заархивировано файлов: ' . $zippedcount . '")</script>';
        }
        ?>
        <?php Pjax::end(); ?>
    </div>
</div>

views/vestnik/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\VestnikSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Вестник Шарьинского района';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container vestnik-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить вестник', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'vest_id',
            //'vest_number',
            //'vest_numberlitera',
            'vest_fullnumber',
            
            [
                'attribute' => 'vest_data',
                'value' => function ($data) {
                    return date('d.m.Y', strtotime($data->vest_data));
                }
            ],
            
            //'vest_pathfile',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/vestnik/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Vestnik */
$litera = $model->vest_numberlitera;
$number = $model->vest_number;
if ($litera){
    $fullNum = $number . '-' . $litera;
} else {
    $fullNum = $number;
}

$this->title = 'Изменение вестника: ' . $fullNum;
$this->params['breadcrumbs'][] = ['label' => 'Вестники', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $fullNum, 'url' => ['view', 'id' => $model->vest_id]];
$this->params['breadcrumbs'][] = 'Правка';
?>
<div class="container vestnik-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vestnik/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Vestnik */

$this->title = 'Вестник №' . $model->vest_fullnumber . ' от ' . date('d.m.Y', strtotime($model->vest_data));
$this->params['breadcrumbs'][] = ['label' => 'Вестники', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container vestnik-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->vest_id], ['class' => 'btn btn-primary']) ?>
        <?=
        Html::a('Удалить', ['delete', 'id' => $model->vest_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Действительно удалить' . $this->title . '?',
                'method' => 'post',
            ],
        ])
        ?>
    </p>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'vest_fullnumber',
            [
                'attribute' => 'vest_data',
                'value' => date('d.m.Y', strtotime($model->vest_data)),
            ],
            'vest_pathfile',
        ],
    ])
    ?>

</div>